### ISSUE TITLE
weightedMetamorphosis_3D.py   TypeError: Not a Tensor type. Got: <class 'int'>.

### ISSUE THREAD

**Issue by lzx-dev** [antonfrancois/Demeter_metamorphosis#1]
mt.Metamorphosis_path gives a TypeError on sigma_v

**Comment by antonfrancois** [comment]
Can you be a bit more specific? Maybe provide a snippet for me to reproduce the bug. Anyway, Demeter has undergone a big transformation lately, let me know if you still encounter the problem.

**Comment by antonfrancois** [comment]
Because of a lack of activity, I close this issue.
