### ISSUE TITLE
issue about 3D images

### ISSUE THREAD

**Issue by 18370029656** [antonfrancois/Demeter_metamorphosis#2]
Hello, may I ask if this code can be used for 3D images

**Comment by antonfrancois** [comment]
Hello, 
Yes it does! Simply pass a Tensor of size [B,C,H,W,D] into the appropriate functions. However, the plot() methods within the class inherited from `Geodesic_intergrator` and `Optimize_geodesicShooting` will not work. (It will come in due time) For now, you will need to implement your own visualisations methods or use the functions within the file `image_3D_visualisation`.
Let me know if you have further questions.
